### ISSUE TITLE
How would you use a .env file that is in a different directory

### ISSUE THREAD

**Issue by nh916** [henriquebastos/python-decouple#105]
I have a .env file that is in a different directory than the root directory and I noticed that python-decouple does not find it and only finds .env file if it is within the root directory. I was wondering how I can specify the path to my .env file

**Comment by nh916** [comment]
```python

from decouple import Config, RepositoryEnv

DOTENV_FILE = '/opt/envs/my-project/.env'
env_config = Config(RepositoryEnv(DOTENV_FILE))

# use the Config().get() method as you normally would since 
# decouple.config uses that internally. 
# i.e. config('SECRET_KEY') = env_config.get('SECRET_KEY')
SECRET_KEY = env_config.get('SECRET_KEY')
```

**Comment by xshapira** [comment]
This also works for me:

```from decouple import AutoConfig```

```bash
config = AutoConfig(search_path="./.envs/.local/")

SECRET_KEY = config('SECRET_KEY')
```
Considering you have this ```./.envs/.local/.env```
