### ISSUE TITLE
How to give path of .env files?

### ISSUE THREAD

**Issue by talhaanwarch** [henriquebastos/python-decouple#106]
I want to know if I put my env in another directory of server for security purpose. How do decouple know where it is located.

**Comment by henriquebastos** [comment]
It searches recursively on parent directories. If you choose some other
branch, you'll have to inform it to decouple.

**Comment by talhaanwarch** [comment]
how can i inform the path? i mean how can I pass the argument, or set the path

**Comment by madjaqk** [comment]
I don't know if this is documented anywhere, but this is what I was able to work out from looking through the code:

```python
from decouple import Config, RepositoryEnv

config = Config(RepositoryEnv("path/to/env_file"))
```

I would also like to know if there's a better/more official way I should be doing this.

**Comment by sidmitra** [comment]
Along similar lines, I have multiple env files eg. `.env.local` or `.env.ci` and in some cases i want to be able to run the same code/server with different env files. I couldn't find a way to get decouple to change the name of the file, atleast from reading the code.

I could probably modify the code from @madjaqk a bit to do it this way.

```python
import os
from decouple import Config, RepositoryEnv

DOTENV_FILE = os.environ.get("DOTENV_FILE", ".env") # only place using os.environ
config = Config(RepositoryEnv(DOTENV_FILE))
```

That would allow me to do something like this.

```bash
DOTENV_FILE=".env" python server.py # or at a different terminal
DOTENV_FILE=".env.second" python another_server.py
```

I will try it out later today. 


Not sure if this feature is useful enough for others to include. Or if it's already built-in somehow and i missed it, feel free to point me to it.

**Comment by henriquebastos** [comment]
> how can i inform the path? i mean how can I pass the argument, or set the path

@talhaanwarch you should protect your code from having to deal with server layout particularities. What I do is, during build/deployment, simple add a symlink to a read only file as .env and all would workout fine.

**Comment by henriquebastos** [comment]
> If so, i can send a PR to support a dynamic `SUPPORTED` var.

Thank you, @sidmitra. But this would work against python-decouple’s design assumptions.

As explained before, the whole idea is that your code should be decouples from instance configuration and layout.

**Comment by henriquebastos** [comment]
> I don't know if this is documented anywhere, but this is what I was able to work out from looking through the code:
> 
> ```python
> from decouple import Config, RepositoryEnv
> 
> config = Config(RepositoryEnv("path/to/env_file"))
> ```
> 
> I would also like to know if there's a better/more official way I should be doing this.

That’s the right way to do it @madjaqk. It's not documented because it is not encouraged. Your code should not know about it’s config file. From your code perspective everything is up and running from proper environment variables.

**Comment by henriquebastos** [comment]
Replied every one. Closing now.

**Comment by halla** [comment]
I may be overlooking something but I fail to see the downside in @sidmitra 's solution. To me it seems to decouple things even more, in this case from the specific project layout with predefined name and location for the config file.

**Comment by henriquebastos** [comment]
Hi @halla. The lib is already decoupled from the `.env` file since you can specify an alternative. I rather not introduce an environment variable into a lib that processes environment variables.

**Comment by halla** [comment]
Right, I would probably also avoid a separate feature now that I think of it, as there is an easy solution already. I guess I was reacting more to the decision not to document it (which was actually an answer to another similar solution but without the environment variable part, to be exact).

**Comment by ruskirin** [comment]
On ubuntu 20.04, python==3.10.9, python-decouple==3.8, default config import does not find the <code>.env</code> file inside my project directory. But if you look at the source, <code>config</code> is just an empty instantiation of <code>AutoConfig</code>, so you can alternatively just:
<code>
    from decode import AutoConfig
    ...
    config = AutoConfig('path/to/env')
    ...
    a = config('A')
    ...
</code>
