### ISSUE TITLE
Custom Config Loaders

### ISSUE THREAD

**Issue by aaronclong** [henriquebastos/python-decouple#108]
I wonder if a custom config source could be added through an external library that acts as an extension. There are cases where these values come from through from [AWS Secretes Manager](https://aws.amazon.com/secrets-manager/), [Vault](https://www.vaultproject.io/), or [Consul](https://www.consul.io/), and this library doesn't support those mechanisms.

If a standard interface could be designed with a way to register it, it could be pretty powerful!!

**Comment by henriquebastos** [comment]
You mean register custom repositories so the data source would change from a .env file to something else?

This would have to be consistent with env variables overwrite.

**Comment by henriquebastos** [comment]
You can use the Repository base class to implement your own.
