### ISSUE TITLE
cannot import 'config' from 'decouple'

### ISSUE THREAD

**Issue by alexshcer** [henriquebastos/python-decouple#109]
![image](https://user-images.githubusercontent.com/64084172/115705050-adffc680-a389-11eb-8b09-1cb5b54a1a90.png)
![image](https://user-images.githubusercontent.com/64084172/115705083-b821c500-a389-11eb-8188-477207f73652.png)

**Comment by pythoninthegrass** [comment]
Sounds related to #88 and #98.

I fixed it in `pipenv` by running
```bash
pipenv run pip uninstall decouple
pipenv install python-decouple
```

**Comment by heljhumenad** [comment]
Yes i also encouter this in python-decouple == 3.4 the config module has been missing or deleted

**Comment by henriquebastos** [comment]
There is a library called decouple, but this is python-decouple.
