### ISSUE TITLE
Value ending and starting with quote marks " or '

### ISSUE THREAD

**Issue by Hatell** [henriquebastos/python-decouple#123]
If I have value starting and ending with quote ' or " in .env -file then quotes are removed from value.

I have a password `'hello'` and I would like to pass it to .env -file like this
```
PASS="'hello'"
```

This isn't possible because decouple.py:132 line strip all `'` or `"` characters from begin and end of the string v.
```
v = v.strip('\'"')
```

Instead of that I would do the removing of quotes like this
```
v = v[1:-1]
```

**Comment by henriquebastos** [comment]
This is a relevante issue. It seems related to #103.

If you can provide a PR improving the test code I would be glad to take a look.
