### ISSUE TITLE
distutils DeprecationWarning in Python 3.10

### ISSUE THREAD

**Issue by iurisilvio** [henriquebastos/python-decouple#127]
> lib/python3.10/site-packages/decouple.py:8: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
>    from distutils.util import strtobool

**Comment by davidfilat** [comment]
I have the same issue

**Comment by apoclyps** [comment]
relates to:
- https://github.com/henriquebastos/python-decouple/pull/128
