### ISSUE TITLE
Compatibility problems with ipython notebook

### ISSUE THREAD

**Issue by nunesvictor** [henriquebastos/python-decouple#13]
Hi there,

I'm have some problems when trying integrate ipython notebook on my decouple using django project. I'm using a virtualenv, so... the problem is my manage.py shell run just fine, decouple recover the values from .env file like charm, but when I'm using ipython notebook I'm getting this exception:

/home/nunesvictor/dev/sisref/env/local/lib/python2.7/site-packages/decouple.pyc in get(self, option, default, cast)
     62 
     63         if isinstance(value, Undefined):
---> 64             raise UndefinedValueError('%s option not found and default value was not defined.' % option)
     65 
     66         if isinstance(cast, Undefined):

UndefinedValueError: SECRET_KEY option not found and default value was not defined.```

My settings.py is configured like these:

SECRET_KEY = config('SECRET_KEY')

I wonder why decouple is incapable to get the value of my SECRET_KEY of the .env file, is this really an issue, or I'm just getting the configuration wrong?! Tks

PS. I'm using django_notebook (https://github.com/benthomasson/django_notebook)

**Comment by henriquebastos** [comment]
Can you provide a repository for me to clone and reproduce the problem?

**Comment by rolando** [comment]
Related: https://github.com/henriquebastos/python-decouple/pull/28

**Comment by henriquebastos** [comment]
I'll check this out next week and make a release enabling you to define the
config path.

**Comment by nunesvictor** [comment]
The pull-request #28 actually solved my problem. thumbs up to it

**Comment by henriquebastos** [comment]
Fixed tks to @rmax!

**Comment by rmax** [comment]
@henriquebastos Great! We will look forward for the new release on pypi.
