### ISSUE TITLE
Feature Request / Console input

### ISSUE THREAD

**Issue by croepha** [henriquebastos/python-decouple#16]
It would be cool if there were a way to ask the console for config input if its not set in environment or settings file.

This functionality should probably only be enabled if it detects a tty console, or maybe an INTERACTIVE=1 env var....

Anyway, this is pretty minor.  If I have some free time in the near future, I'll do a PR

**Comment by henriquebastos** [comment]
I'm planning to implement the default unix behavior for envvars and config files so you'll can easily do: `SOMEVAR=VALUE python my_decouples_project.py`

So you can easily override whatever you want during development.
