### ISSUE TITLE
Casting to json raising SyntaxError

### ISSUE THREAD

**Issue by cyrilchampier** [henriquebastos/python-decouple#171]
Hello, thank you for your work on this package!

I encounter an unexpected behavior while trying to load json values.
I am missing something, or `callable(config)` should be stricly equivalent to `config(cast: callable)`?

```
$ SIMPLE_JSON='{"good":true}' python manage.py runserver
> /Users/xxxx/src/xxx/settings.py(30)<module>()
(Pdb) config('SIMPLE_JSON')
'{"good":true}'
(Pdb) json.loads(config('SIMPLE_JSON'))
{'good': True}
(Pdb) config('SIMPLE_JSON', cast: json.loads)
*** SyntaxError: invalid syntax
```

**Comment by tyler46** [comment]
hey @cyrilchampier, I think that the following:

```python
config('SIMPLE_JSON', cast: json.loads)
```

needs to become:

```python
config('SIMPLE_JSON', cast=json.loads)
```

**Comment by cyrilchampier** [comment]
🤦 
You are completely right!
Thank you, and sorry for that mistake!
