### ISSUE TITLE
Fix the difference between the way python and ipython do recursive searches.

### ISSUE THREAD

**Issue by israelst** [henriquebastos/python-decouple#19]
Assuming that the intended behaviour is to recursively searches up your configuration module path looking for a `settings.ini` or a `.env` file, given the following directory tree:
- settings.ini
- code.py
- folder
  - deeper_code.py

with the following content:

``` ini
[settings]
SOME_VAR = value
```

``` python
# code.py
from decouple import config

print(config('SOME_VAR'))
```

``` python
# deeper_code.py
from decouple import config

print(config('SOME_VAR'))
```

I've tried:

``` bash
$ ipython code.py
value
$ python code.py
value
$ ipython folder/deeper_code.py
value
$ python folder/deeper_code.py
Traceback (most recent call last):
  File "folder/deeper_code.py", line 3, in <module>
    print(config('SOME_VAR'))
  File "~/.virtualenvs/decouple-test/lib/python3.4/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "~/.virtualenvs/decouple-test/lib/python3.4/site-packages/decouple.py", line 77, in __call__
    return self.get(*args, **kwargs)
  File "~/.virtualenvs/decouple-test/lib/python3.4/site-packages/decouple.py", line 64, in get
    raise UndefinedValueError('%s option not found and default value was not defined.' % option)
decouple.UndefinedValueError: SOME_VAR option not found and default value was not defined.
```

running ipython 4.0.0 over python 3.4.0 and python 3.4.0 alone. 

Looking for some explanations, I've seen that ipython and python have a different return for [the magic](https://github.com/henriquebastos/python-decouple/blob/master/decouple.py#L190)  `frame.f_back.f_back.f_code.co_filename`. The first returns an absolute path and the second a relative one.

So, as the magic depends on [a function that should only be used internally](https://docs.python.org/2/library/sys.html#sys._getframe), and given the behaviour described, could we replace it for something like `path = os.path.abspath('.')` or add `path = os.path.abspath(path)`? If so, I will be happy to offer a pull request.

**Comment by henriquebastos** [comment]
Yes!

Right now you could do:

```
from decouple import Config, RepositoryIni
config = Config(RepositoryIni('/path/to/settings.ini/'))
print(config('SOME_VAR'))
```

However, this shows a problem with the API. I think we could improve the relationship between `Config` and the `Repository` so we could do something like:

```
from decouple import Config
config = Config('/path/to/settings.ini/')
print(config('SOME_VAR'))
```

**Comment by rolando** [comment]
This PR https://github.com/henriquebastos/python-decouple/pull/28 could fix this issue by allowing users to do:

```python
# Make search path consistent between python and ipython interpreter.
config = AutoConfig(os.getcwd())  # or os.path.realpath(os.path.dirname(__file__))
```
