### ISSUE TITLE
decouple get .env file from two parent folders of the project.

### ISSUE THREAD

**Issue by luzfcb** [henriquebastos/python-decouple#20]
I do not have a .env file in the project folder, but I have one in a folder at the top parent directory outside of project folder. Decouple are reading this file.

```
/home/user/repository/
    | .env # decouple should not read this file
    | github/
        | projects/
            | myproject /
                | manage.py
                | myproject/
                    | settings.py
                    | urls.py
                    | wsgi.py
                | app1/
```

**Comment by henriquebastos** [comment]
Yes, decouple searches recursively for a .env file.

What different behavior do you need?

**Comment by luzfcb** [comment]
I expect him to read recursively only within the current project folder, not the any parent folder of current project folder.

It took me a long time to figure out where he was getting the configuration, because, in the folder of the current project, there is no .env file and none of the directories parent of the current project folder is listed in PYTHONPATH.

It is a completely unexpected behavior

**Comment by luzfcb** [comment]
Eu espero que ele leia recursivamente somente dentro da pasta do projeto atual, não a pasta pai da pasta qualquer projeto atual.

Levei muito tempo para descobrir onde ele estava recebendo a configuração, porque, na pasta do projeto atual, não há nenhum arquivo .env e nenhum dos diretórios pai da pasta do projeto atual está listado em PYTHONPATH.

É um comportamento completamente inesperado

**Comment by henriquebastos** [comment]
> Maybe we could make it more explicit on the docs.

Decouple knows nothing about the python path.

I plan to improve the Config class so you can define a specific path without recursion.

The generic config is a AutoConfig instance and it's supposed to search recursively for the .env file.

**Comment by luzfcb** [comment]
I'm no free time at the moment, but then I try to create a sample project to try to reproduce the problem.

**Comment by henriquebastos** [comment]
Acho que eu entendi o seu problema. Só que há um conflito entre a forma q
vc organiza suas coisas e o comportamento padrão do decouple.

**Comment by luzfcb** [comment]
oh God, havia esquecido completamente disto aqui.

**Comment by fandrefh** [comment]
Nesse momento estou tendo problemas,eu coloquei o .env dentro de um diretório chamado config, no mesmo nível do settings.py, e estou recebendo a mensagem de erro de que a chave SECRET_KEY não está sendo localizada.

Já inclusive adicionei esse diretório no PATH do projeto mas mesmo assim o erro permanece.

**Comment by henriquebastos** [comment]
Existe SECRET_KEY no .env? O formato da linha está correto?

Pode descrever a estrutura de diretórios precisa pra eu poder reproduzir o
problema?

**Comment by fandrefh** [comment]
Sim, existe a chave e está assim minha estrutura.

```
.
├── project_django
│   ├── config
│   │   └── .env
│   │   └── requirements.txt
│   ├── costumers (django app)
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
├── manage.py
```
Dentro do `.env` está assim:
SECRET_KEY=my_secret_key_here
DB_HOST=...
DB_NAME=....

No `settings.py` está assim:

`SECRET_KEY = config('SECRET_KEY')`

**Comment by henriquebastos** [comment]
A detecção automática precisa que o `.env` esteja no mesmo diretório ou em
diretório superior ao `settings.py`.

Nesse layout não funciona automático.

Vc precisará indicar onde o decouple deve procurar manualmente no seu
settings.py usando algo como:

```python
from os.path import dirname, join, sep
from decouple import AutoConfig

dir = join(dirname(__file__), sep, 'config')

config = AutoConfig(search_path=dir)
```

**Comment by fandrefh** [comment]
Cara, acho que fiz exatamente como falou pra fazer, mas mesmo assim não deu.

```
import os
from decouple import AutoConfig

CONFIG_DIR = os.path.join(os.path.dirname(__file__), os.path.sep, 'config')
config = AutoConfig(search_path=CONFIG_DIR)

SECRET_KEY = config('SECRET_KEY')
```
Continuo com o mesmo erro.

**Comment by solababs** [comment]
@fandrefh 

**remove `os.path.sep` **

`import os
from decouple import AutoConfig

CONFIG_DIR = os.path.join(os.path.dirname(__file__), 'config')
config = AutoConfig(search_path=CONFIG_DIR)

SECRET_KEY = config('SECRET_KEY')
`

**Comment by luzfcb** [comment]
@henriquebastos aparentemente, `AutoConfig` não está respeitando `search_path`

tendo um arquivo `.env` com o seguinte conteudo:

```
SECRET_KEY=segredosecreto
```
e tendo a seguinte estrutura de diretórios:

```
(myproject) fabio@luzfcb:~/projects$ tree myproject -L 2
myproject
├── .env
├── README.md
├── backend
│   ├── README.md
│   ├── myproject/
│   ├── configure_django.py  # decouple está aqui
│   └── serverless.yml
├── buildspec.yaml
├── cloudformation
│   └── dev-resources.yaml
├── codecov.yml
├── requirements.txt
├── requirements_dev.txt
├── setup.cfg
├── testspec.yaml
└── tox.ini
```

em `configure_django.py`

```
import os
from decouple import AutoConfig

PROJECT_ROOT = os.path.dirname(os.path.dirname(__file__))

config = AutoConfig(search_path=PROJECT_ROOT)

SECRET_KEY = config('SECRET_KEY')
print("SECRET_KEY: {}".format(SECRET_KEY))

```

se, dentro da pasta myproject/backend eu fizer:

```
(myproject) fabio@luzfcb:~/projects/myproject/backend$ python configure_django.py
SECRET_KEY=segredosecreto
```

e depois executar mover o arquivo .env para o HOME

```
(myproject) fabio@luzfcb:~/projects/myproject/backend$ mv ../.env $HOME/.env
```

e fizer novamente

```
(myproject) fabio@luzfcb:~/projects/myproject/backend$ python configure_django.py
SECRET_KEY=segredosecreto
```
