### ISSUE TITLE
How to use decouple with a regular python library?

### ISSUE THREAD

**Issue by fccoelho** [henriquebastos/python-decouple#22]
I am using decouple with a library I am developing.
It works just fine when I am testing it from the development directory. However after I install the library and try to import it from a python process started on a arbitrary directory, it cannot find the settings.ini even if I copy it to the directory I am starting python from.

In such cases, where should the settings.ini be placed? this should be made clear in the documentation.

**Comment by henriquebastos** [comment]
When you `from decouple import config` you're using the default [AutoConfig](https://github.com/henriquebastos/python-decouple/blob/master/decouple.py#L147) instance.

It has a [magic](https://github.com/henriquebastos/python-decouple/blob/master/decouple.py#L187) that searches for the settings.ini file from the caller's module directory. If it can't find there, [it keeps searching up the tree](https://github.com/henriquebastos/python-decouple/blob/master/decouple.py#L159).

If you want to have full controle and point directly where your settings.ini is:

```
from decouple import RepositoryIni, Config
config = Config(RepositoryIni('path/to/settings.ini'))

DEBUG = config('DEBUG')
```

This API has room for improvement. You're the 2nd to request something like this.

**Comment by nielsonsantana** [comment]
I have interest in this feature too. I solve it by override `_caller_path`

    from decouple import AutoConfig

    def _caller_path(self):
        return os.getcwd()

    AutoConfig._caller_path = _caller_path
    config = AutoConfig()

**Comment by henriquebastos** [comment]
@nielsonsantana can you provide a patch so we can invert the dependency on the path?

**Comment by nielsonsantana** [comment]
I trying figure out where I put change your code. Are you suggesting to override "_caller_path"?
Replace:

    def _caller_path(self):
        # MAGIC! Get the caller's module path.
        frame = sys._getframe()
        path = os.path.dirname(frame.f_back.f_back.f_code.co_filename)
        return path 

for 

    def _caller_path(self):
        return os.getcwd()

In my tests, it's work based on where it is called from. Per example, if it is called from a terminal, it will use the local `.env` based on the path of the terminal.

**Comment by osantana** [comment]
I'd like to make a design suggestion: avoid configuration handling in libraries. The "right place" to handle configuration is your project (that requires/uses the library).

It's better make your library configuration-agnostic, so, the users of your library can use any configuration system. And you can also reduce the number of depedencies.

## "Wrong" way

```python
# mylib.py

class Client:
    def __init__(self, url=None):
        self.url = config("URL", default="http://localhost/")
```

```python
# myproject.py

from mylib import Client

client = Client()
```

## "Right" way

```python
# mylib.py

class Client:
    def __init__(self, url):
        self.url = url
```

```python
# myproject.py

from mylib import Client

url = config("URL", "http://localhost")
client = Client(url)
```

**Comment by rolando** [comment]
I faced this issue when trying to use `decouple.config` in a jupyter notebook.

This PR https://github.com/henriquebastos/python-decouple/pull/28 allows the users to instantiate `AutoConfig` with a custom initial search path. For example, in a jupyter notebook:

```python
config = AutoConfig(os.getcwd())
```

**Comment by henriquebastos** [comment]
Fixed tks to @rmax
