### ISSUE TITLE
Use # and utf-8 in Csv parsing

### ISSUE THREAD

**Issue by thiagogds** [henriquebastos/python-decouple#24]
The Csv parsing uses `shlex` and it usually escape `#` beacuse it is a comment char.
Also it don't support UTF-8 chars.

@henriquebastos Do you think it's better to keep this way or change it?

**Comment by henriquebastos** [comment]
I don't know. The original Csv was meant to show decouple's capabilities. Can you list examples you wish to use?

Maybe we need more Csv "modes".

**Comment by thiagogds** [comment]
I'm getting twitter search track terms from the settings. So I need to use # "Hashtags" and utf-8 char.

I need things like #VotaçãoDoImpeachment

For now I've created my own parser based on the Csv inside my project and it's fine.

**Comment by henriquebastos** [comment]
Maybe you could contribute your parser to decouple so we can compare. It
seams to be a simple Spliter.

**Comment by thiagogds** [comment]
No it's not hahaha I just configured the shlex to ignore comments and decoded the value to utf-8
;) Em seg, 18 de abr de 2016 às 22:59, Henrique Bastos <notifications@github.com>
escreveu:
Maybe you could contribute your parser to decouple so we can compare. It
seams to be a simple Spliter.

**Comment by henriquebastos** [comment]
So maybe you can add args to Csv constructor to enable this configuration on each instance. ;)

**Comment by thiagogds** [comment]
I will open a PR with It :D

Em qua, 20 de abr de 2016 07:01, Henrique Bastos <notifications@github.com>
escreveu:
