### ISSUE TITLE
Bug: call os.environ.get(key) generate " KeyError: "

### ISSUE THREAD

**Issue by nielsonsantana** [henriquebastos/python-decouple#27]
The python-decouple are calling 'os.environ.get(key)', but the better approach is 'os.environ.get(key, '')', passing a empty string.

**Comment by nielsonsantana** [comment]
The error are in self.data[key], when I set a empty variable on .env.
Example, `CDN_PREFIX=""`, this cause error because the key would is in 'os.environ', but as it is empty, the decouple try get from self.data.


```
class RepositoryEnv(RepositoryBase):
    """
    Retrieves option keys from .env files with fall back to os.environ.
    """
    def __init__(self, source):
        self.data = {}

        for line in open(source):
            line = line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            k, v = line.split('=', 1)
            k = k.strip()
            v = v.strip().strip('\'"')
            self.data[k] = v

    def __contains__(self, key):
        return key in os.environ or key in self.data

    def get(self, key):
        return os.environ.get(key) or self.data[key]
```

**Comment by henriquebastos** [comment]
Tks, @nielsonsantana! This report helped improve things quite a bit.

Check out at https://github.com/henriquebastos/python-decouple/commit/63d3fc3c3553f3c575a41eb4d69b9fa74aca8f75
