### ISSUE TITLE
Support for dict as a cast argument

### ISSUE THREAD

**Issue by tadeoos** [henriquebastos/python-decouple#35]
Hey,

I was wondering what are your thoughts about extending current functionality with a possible "cast as dict" feature.

In Django for example, the 'DATABASES' setting varies from deploy to production and it is quite nice and easy (although I admit, a little brute) to just keep the entire db dict as a string in .env file

This fix makes it possible to just do:

in .env:

```console
DATABASES={'default': {'ENGINE': 'db.backend', 'NAME': '/absolute/path/to/your/db.sqlite3',}} 
```

and in settings.py:

```python
DATABASES = config('DATABASES', cast=dict)
```

I've forked the repo and implemented the change (using literal_eval function) so am ready for PR.

What do you think?

**Comment by henriquebastos** [comment]
Can you share your code strategy? I feel this shouldn't be inside decouple, but could be a helper `dictionary` cast function like `Csv`.

I have a personal preference for strategies like [dj-database-url](https://github.com/kennethreitz/dj-database-url) that converts an URL to a `DATABASE` dictionary. For quite some time I though about including it as a dependency. However this seems too specific for Django.

**Comment by meiralins** [comment]
@henriquebastos he already implemented it [here](https://github.com/tadeoos/python-decouple/commit/d4d9cb7358044c21cfae49276ac84f5696903be8)

To be honest, storing a database as a dict looks really strange and it makes it harder to read the contents of the variable. Imagine someone changing it in a .env file, it wouldn't be that easy. I feel this shouldn't be in decouple too.

You really should be using dj-database-url or multiple variables.

**Comment by tadeoos** [comment]
Actually I totally agree. Thanks for _dj-database-url_, haven't heard of it. Actually my PR is totally unnecessary since you can already obtain the desired behavior, simply by passing the `literal-eval` function as the `cast` argument. I checked it out afterwards and didn't cancel my PR... Sorry

**Comment by henriquebastos** [comment]
Cool! Tks for the PR and the discussion! :)
