### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Lrcezimbra** [henriquebastos/python-decouple#44]
The project have a changelog file?

If not, I suggest that create one to facilitate the follow-up of version updates.

**Comment by henriquebastos** [comment]
Cool idea. A PR would be welcome. I do use tags to release it. Maybe there
some general strategy to combine commit messages with the change log.

Em 9 de ago de 2017 3:47 PM, "Lucas Rangel Cezimbra" <
notifications@github.com> escreveu:

**Comment by Lrcezimbra** [comment]
Great, I'll create a pull request.
