### ISSUE TITLE
Allow to specify config file path

### ISSUE THREAD

**Issue by sobolevn** [henriquebastos/python-decouple#50]
First of all, thanks for this project!

I prefer to keep my `.env` files inside `config/` folder. I also prefer to name it differently, like `prod.env` or `secret.env`.

Here's a live example: https://github.com/wemake-services/wemake-django-template

Can I do that? If not, would you mind a PR for this?
Do you have any suggestions on how it should be implemented?

Cheers!

**Comment by henriquebastos** [comment]
To answer I need to break you question in 2 parts:

**1)** You can explicitly inform the path where starts.

[Check out the doc for AutoConfig.](https://github.com/henriquebastos/python-decouple#id11)

**2)** You shouldn't use different filenames to different environments. I understand that in your repository you want to keep the config files as backup. But from your project's code perspective, it should not know if it's *production* or *staging* or *a demo for a potential customer*.

Decouple's purpose is to separate config from code.

**Comment by sobolevn** [comment]
Fair enough! I will rename this file. And specify a path. Thanks!
