### ISSUE TITLE
Add yml support.

### ISSUE THREAD

**Issue by ramiroluz** [henriquebastos/python-decouple#51]
The yml support is largely used in several libs, like ansible.

The format allows very clear configuration and improve the readability.

Thanks for your work, very useful lib.

**Comment by henriquebastos** [comment]
I've explained on #46 why yaml is not good for decouple.

However, if you can demonstrate how this relates to ansible and how having yaml would make your life easier with ansible, I'm may reconsider. ;)

**Comment by sidmitra** [comment]
I'm not OP, but i do think @ramiroluz has a point. It seems a lot of devops tools like ansible and more recently gcloud(Google Cloud SDK) have started using YAML for environment variables. 
See here https://cloud.google.com/sdk/gcloud/reference/beta/functions/deploy

```
--env-vars-file=FILE_PATH
Path to a local YAML file with definitions for all environment variables. All existing environment variables will be removed before the new environment variables are added.
```
 
So for Google cloud functions on local i'm using .env files and then in my CI/CD system i have a `stage.env.yaml` file to pass staging vars to the deploy command. So for the same thing i end up using two different formats. 
Here's a sample YAML file
```
MONGODB_USERNAME: blah
MONGODB_PASSWORD: foo
MONGODB_HOST: 111.111.111.111
MONGODB_PORT: "27017"
DEFAULT_DB: mydb
ENABLE_SOMETHING: "True"    # in quotes because gcloud sdk weirdly complains about finding bool instead of str, same for int
````

There's actually a also third file with environ variables in my project, which are using for running test cases using `pytest-env`. 

I'd be fine with `.env` as a standard everywhere but it seems a lot of companies are settling on yaml for this, so it might be worth looking at this feature request again.
