### ISSUE TITLE
Feature request: allow to dump config to dict

### ISSUE THREAD

**Issue by xliiv** [henriquebastos/python-decouple#55]
It'd be nice to allow casting config to dict.. .

```
from decouple import config
dict_config = dict(config)  # or other way of getting this result
assert dict_config['SECRET_KEY'] == config('SECRET_KEY')
```

Then one could easily load it to flask:
https://github.com/pallets/flask/blob/f18fe15e6d9b02631e9ff24ab3c1660b8ba28f94/flask/config.py#L198

**Comment by henriquebastos** [comment]
Sounds interesting implementing `__iter__` or a `items` method for config.

The 1st would be easier, but the 2nd would be respect `dict`'s api.

**Comment by nikolaevigor** [comment]
Hi, @henriquebastos .
May be do it like so:

```python
class RepositoryIni:
    ...
    def items(self):
        return self.parser.items(self.SECTION)


class AutoConfig:
    ...
    to_dict(self):
        items = self.repostiory.items()
        return {k.upper(): v for k,v in items}
```

Could it work?

**Comment by henriquebastos** [comment]
It's important to be consistent across repositories.

Also, the repositories are already similar to key/value stores. So it seems
better for items function to return a tuple of tuples on the form: ((k1,
v1), (k2, v2), (kn, vn))

So we wouldn't need the to_dict funcion and could simply
dict(config.items()).

Em 1 de fev de 2018 15:17, "Igor Nikolaev" <notifications@github.com>
escreveu:

**Comment by henriquebastos** [comment]
I tried to play with your PR, however you're only testing against string values.

What would happen in the case of a `bool`?

For exemple:

```
assert dict(config.items())['KeyTrue'] == 'True'
```
Would you expect the above value to be the _string 'True'_ or the _boolean value True_?

The former is not possible without calling config.

This makes this feature a **no go**.

If you need to retrieve many keys as a dict you can simply do:

```
d = {k: config(k) for k in ('Key1', 'Key2', 'Key3', 'KeyN')}
```

If you have any other consideration, I'll be happy to read. For now I'm closing the issue.
