### ISSUE TITLE
More documentation/examples using RepositoryEnv, RepositoryIni

### ISSUE THREAD

**Issue by Nebuchadrezzar** [henriquebastos/python-decouple#60]
If the documentation had spelled out that AutoConfig is the default and examples of RepositoryEnv/Ini that would have been helpful. Perhaps it is only a matter of adding a more few examples? For instance, if I found something like this, it would have been helpful: 

```
from decouple import Config, RepositoryEnv
 
keypath = os.path.join(os.path.dirname(BASE_DIR), 'keys/.env')
config = Config(RepositoryEnv(keypath))
SECRET_KEY = config('SECRET_KEY')

```

**Comment by henriquebastos** [comment]
Hi. The proper way is already on the documentation:

![henriquebastos_python-decouple__strict_separation_of_config_from_code_](https://user-images.githubusercontent.com/12066/43984743-d9c374ca-9cd8-11e8-86d4-d5d2b2c4a00d.png)

Feel free to propose a PR to improve it. It's always nice to make thing more clear.
