### ISSUE TITLE
Is this project still mantained?

### ISSUE THREAD

**Issue by alexandremjacques** [henriquebastos/python-decouple#75]
Since last commit appears to be at least 2 years old, should I consider this project abandoned? I ask because some PRs not merged are interesting and I would use those features right away (Docker secrets being a must one right now).

**Comment by soypunk** [comment]
@alexandremjacques you might take a look at 
https://github.com/lincolnloop/goodconf/ and see if it meets your needs... it is fairly similar approach though it prefers JSON/YAML as the serialization format.

**Comment by sant527** [comment]
Can we use this with Django 2.1.7

**Comment by soypunk** [comment]
@sant527 if you are referring to my comment on GoodConf -- yes it works with Django 2.x. I have a couple of apps in production with it now. I haven't tried decouple with Django 2.x but I was going to setup a sample project and see how it goes -- kinda far down my todo list at the moment though.

**Comment by sant527** [comment]
also i heard about django-environ. i am little confused.is there any standard way

**Comment by henriquebastos** [comment]
When I have the time and ppl helps, I do maintain the project.

Many PRs changes lot's of design assumptions and are not good to merge. This is the biggest obstacle. 

However today I just made a new release to solve some important issues.

All the best!
