### ISSUE TITLE
Quotation Marks on values

### ISSUE THREAD

**Issue by rodrigoddc** [henriquebastos/python-decouple#78]
Trying to set value to a password email, the character "quotation mark" ( ' ) is ignore. I have research a lot but i couldn't find how to get it around

For example: 

On .env:

mySMTPEmail=mypassword'

The quote character at the end of password value is ignored. I've tryied double it for closing, but anyway, when i run debugg the password value doesn't get the quote, like:

mySMTPEmail=mypassword  (without quote)

So, can't authenticate on SMTP server

**Comment by carlos-moreno** [comment]
@rodrigoddc from what I understand by parsing decouple.py, this is because of line 132, where the following operation is performed to get the value of the currently read key.
```
v = v.strip().strip('\'"')
```
