### ISSUE TITLE
Config.get returning default value without cast(value)

### ISSUE THREAD

**Issue by rougeth** [henriquebastos/python-decouple#8]
Wouldn't make more sense to return **default** value in the way it was defined?

For example, in Django, we know that *ALLOWED_HOSTS* is a list, but if we call config with *default=[]*, it returns an error (using the example code in README):

```python
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[],
                       cast=lambda v: [s.strip() for s in v.split(',')])
```

**Comment by henriquebastos** [comment]
Try `list` instead of `[]`. It's a callable and should work.

**Comment by henriquebastos** [comment]
Sorry. I misread `default` for `cast`. Can you provide the error message and/or a failing test?

**Comment by rougeth** [comment]
```
  File ".../settings.py", line 36, in <lambda>
    cast=lambda v: [s.strip() for s in v.split(',')])
AttributeError: 'list' object has no attribute 'split'
```

*decouple* will call `cast(default)`, in [this line](https://github.com/henriquebastos/python-decouple/blob/master/decouple.py#L71). It just seems strange.

**Comment by henriquebastos** [comment]
Hum... ok.

So we have a design decision to discuss. It seems that everything starts with: *What is default?*

Today, `default` is the *fallback string value* for an *undefined* `option`. So if you don't define the `ALLOWED_HOSTS` option, it will use the `default` as input for `cast`.

This enables you to have shorter config files/env by defining sane default values on your python code. Example:

```
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=csv())
```

In the above case, even if you don't define `ALLOWED_HOSTS` on your config file/env it should work fine.

What you seem to be questioning is: *Should default be the end python value or should we have another parameter for that?*

I don't know.

The purpose of *decouple* is to make it easy to load config from text data files/env. Maybe we could improve the documentation to clarify this.

What do you think about it?
