### ISSUE TITLE
add changelog and tags for 3.2 and 3.3 releases

### ISSUE THREAD

**Issue by willkg** [henriquebastos/python-decouple#83]
There's no git tag for the 3.2 and 3.3 releases that happened in November. Can you add/push the git tags?

Also, there's nothing in the CHANGELOG about what changed.

Based on commits, I think the changes are as follows:

python-decouple 3.2:

* fixed typos in documentation
* add editorconfig file
* fix handling for configuration values that end in single or double quotes (#78)
* add support for encoding env files in other encodings (#62) (#64)
* improve csv documentation (#59)

python-decouple 3.3:

* enforce search order in settings files
* switch to using strtobool (#71)

Thank you!

**Comment by henriquebastos** [comment]
Tks, @willkg! Can you provide a PR? I would gladly merge.

**Comment by willkg** [comment]
I threw together #89. Hope that helps!

**Comment by henriquebastos** [comment]
Tks

**Comment by willkg** [comment]
I appreciate you landing the patch, but this issue covered adding tags for 3.2 and 3.3, too. Can you do that, please?

**Comment by henriquebastos** [comment]
Done! ;)

**Comment by willkg** [comment]
Thank you!
