### ISSUE TITLE
Config Import Error

### ISSUE THREAD

**Issue by Nazarenes** [henriquebastos/python-decouple#88]
Hello, when I try to use decouple in a project, I got the following error:

``` python
 from decouple import config
```

Error:

```
ImportError: cannot import name 'config' from 'decouple' (~/.local/lib/python3.7/site-packages/decouple/__init__.py)
```

I'm not sure what went wrong. Thanks!

**Comment by Lrcezimbra** [comment]
How did you install it?
I suspect you have installed [decouple](https://pypi.org/project/decouple/) instead of [python-decouple](https://pypi.org/project/python-decouple/).

To install this lib run:

```
pip install python-decouple
```

**Comment by Nazarenes** [comment]
Yes that's exactly what I did.... I tried `pip3` at first, then tried with `pip` again, and the issue remained there.

**Comment by Nazarenes** [comment]
Okay I think I know why this happened, thank you anyways!
