### ISSUE TITLE
Deprecated use of readfp

### ISSUE THREAD

**Issue by MaximeWeyl** [henriquebastos/python-decouple#92]
Hello,

I get warnings about ConfigParser.reafp when using decouple : 

> [...]\py3.7\lib\site-packages\decouple.py:106: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
    self.parser.readfp(file_)

The warning message suggests using .read_file() instead.

**Comment by henriquebastos** [comment]
Fixed by #121

**Comment by pietrodn** [comment]
Thanks @henriquebastos! Would it be possible to release a bug fix release, please? 🙏🏼
