### ISSUE TITLE
Having problems getting python-decouple to work on AWS.

### ISSUE THREAD

**Issue by theo39** [henriquebastos/python-decouple#94]
not sure how to fix this problem:
https://stackoverflow.com/questions/60733143/how-to-get-python-decouple-to-work-on-a-live-server

**Comment by theo39** [comment]
python-decouple seems to work well when the project is run locally, but when pulled to my AWS Ubuntu server and ran, I get "decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value."

**Comment by henriquebastos** [comment]
The problem is that (1) you don't have your server environment variables set and (2) you don't have a `.env` to work as a fallback.

It seems you're not using the library correctly.

**Comment by theo39** [comment]
I decided to use the AWS parameters instead But thank you for your quick reply.
