### ISSUE TITLE
decouple.UndefinedValueError: SECRET_KEY not found.

### ISSUE THREAD

**Issue by dsbyprateekg** [henriquebastos/python-decouple#99]
Hi,

I am getting following error-

`raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECRET_KEY not found. Declare it as envvar or define a default value.`

Issue seems with the secret key starting with equal to (=) sign. For example with below secret key:
`SECRET_KEY = =xg583qt1rc*lec39dy6mtdlg@#v+m0a51no&2@l9fz^nkh&1f`

**Comment by dsbyprateekg** [comment]
I just found my issue.
It was not due to equal to sign in secret key. In fact I have given my env file a name but it should be only .env.
After changing file from `cred.env` to `.env` it is working.

**Comment by abhishekcaritor** [comment]
add .env file and add this SCOUT_KEY =''
SCOUT_NAME = '' in .env file then pip install scout-apm
then Its working

**Comment by apoorvthedude** [comment]
Hey @dsbyprateekg ,My file name is already .env but still error is coming.


```File "/app/mainproject/settings.py", line 24, in <module>
SECRET_KEY = config('SECET_KEY')
File "/opt/venv/lib/python3.8/site-packages/decouple.py", line 243, in __call__
return self.config(*args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/decouple.py", line 105, in __call__
return self.get(*args, **kwargs)
File "/opt/venv/lib/python3.8/site-packages/decouple.py", line 90, in get
raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: SECET_KEY not found. Declare it as envvar or define a default value.
```

What to do now

**Comment by apoorvthedude** [comment]
Hey @abhishekcaritor,I also tried what you said,but still error is coming.

**Comment by RyanDhingra** [comment]
Has a solution for this been found? I'm having the same issues while trying to deploy my Django API on Pythonanywhere. I've followed the docs word for word and got it setup but am still getting this error.

**Comment by dakash98** [comment]
Hi @apoorvthedude, Please check your .env file. I think it's missing.

**Comment by gentlesoul18** [comment]
> Hi @apoorvthedude, Please check your .env file. I think it's missing.

I am facing this problem and my .env is okay but still getting the error

**Comment by gentlesoul18** [comment]
> Has a solution for this been found? I'm having the same issues while trying to deploy my Django API on Pythonanywhere. I've followed the docs word for word and got it setup but am still getting this error.

How did you solve this, bro?

**Comment by RyanDhingra** [comment]
> > Has a solution for this been found? I'm having the same issues while trying to deploy my Django API on Pythonanywhere. I've followed the docs word for word and got it setup but am still getting this error.
> 
> 
> 
> How did you solve this, bro?
> 
> 
Still unsolved, just switched to Flask and deployed via Render.

**Comment by gentlesoul18** [comment]
Okay, Thank you

**Comment by enyfour5** [comment]
is it possible to create a ".env" file in a dist folder? I keep getting this error and I created the ".env" file in my dist folder but apparently it's not reading it. Any help here is appreciated. I used pyinstaller to create an exe of my python script but keep getting that error. It works outside of my dist folder but not inside my dist folder.

**Comment by henriquebastos** [comment]
@enyfour5 .env is searched starting on the main module directory going upwards on the directory tree. You can specify a file by:

```python
from decouple import Config, RepositoryEnv

config = Config(RepositoryEnv("path/to/env_file"))
```

**Comment by LucasFQuirogaH** [comment]
en settings.py completa la línea como sale debajo:
SECRET_KEY = config('SECRET_KEY', default='mydefaultvalue')

**Comment by Jasur09** [comment]
def set_token(my_secret):
    load_dotenv(find_dotenv)
    TOKEN = os.environ['secret_key']

**Comment by profermarquez** [comment]
in the program file: SECRET_KEY = config('SECRET_KEY')
and in the .env: SECRET_KEY=B!1w8*NAt1T^%kvhUI34g

**Comment by ElinaNeuronUP** [comment]
I had the same error. Surprisingly, after searching for a resolution to this problem, a simple "Restart kernel" finally solved it.

**Comment by thecodewithabhi** [comment]
![Image](https://github.com/user-attachments/assets/c32782b6-7187-4f36-b0fa-30925d09b5f1)

Hi everyone,
I'm getting the following error when I try to run my Django project:
`decouple.UndefinedValueError: SECRET_KEY not found.`

I'm using python-decouple to manage my environment variables. In my settings.py, I have:

> from decouple import config

> SECRET_KEY = config('SECRET_KEY')

I’ve already created a .env file in the root directory of my project with this line:

`SECRET_KEY=my-very-secret-key`
But the error still appears. I’ve checked that the .env file exists and contains the key.

Can someone please help me figure out what might be wrong?
Is there something I’m missing with how decouple loads the .env file?

Thanks in advance!
